services:
  nuxt:
    container_name: docus
    restart: always
    build:
      context: apps/docus
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - "8001:3000"
    volumes:
      - ./apps/docus:/app
      - /app/node_modules

  api:
    container_name: doc-to-llm
    env_file:
      - .env
    build:
      context: apps/server
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./apps/server:/src
    restart: always