services:
  api:
    container_name: doc-to-llm
    platform: linux/amd64
    env_file:
      - .env
    build:
      context: apps/server
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./apps/server:/src
    restart: always