services:
  api:
    container_name: doc-to-llm
    platform: linux/amd64
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    restart: always