name: CI – Linting

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        description: Python version used to run lint
        required: true
        type: string
  workflow_dispatch:
    inputs:
      PYTHON_VERSION:
        description: Python version used to run lint
        required: true
        type: string
        default: 3.X

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python ${{ inputs.PYTHON_VERSION }}
        run: uv python install ${{ inputs.PYTHON_VERSION }}

      - name: Install dependencies
        working-directory: ./apps/server
        run: |
          uv sync --dev

      - name: Lint with ruff
        working-directory: ./apps/server
        run: |
          uv run ruff check .
          uv run ruff format --check .
